# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
