# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170521_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
    ]
